[workspace]

members = [
  "iroha",
  "iroha_client",
  "iroha_client_no_std",
  "iroha_client_cli",
  "iroha_macro",
  "iroha_macro/iroha_derive",
  "iroha_network",
#  "iroha_substrate/parachain",
#  "iroha_substrate/parachain/runtime",
#  "iroha_substrate/parachain/runtime/collator",
  "iroha_substrate/substrate-node-template/node",
  "iroha_substrate/substrate-node-template/pallets/template",
  "iroha_substrate/substrate-node-template/pallets/collateral",
  "iroha_substrate/substrate-node-template/pallets/x-core",
  "iroha_substrate/substrate-node-template/runtime",
]
